# Generated by Django 4.2.5 on 2024-01-26 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ispatient',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
