# Generated by Django 4.2.5 on 2024-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('scan', models.ImageField(upload_to='scans')),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
    ]
