# Generated by Django 4.2.5 on 2024-01-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='problem',
        ),
    ]
