# Generated by Django 4.2.5 on 2024-01-26 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='problem',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scan',
            field=models.ImageField(upload_to='scans'),
        ),
    ]
